apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ws-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice
        image: eu.gcr.io/sandbox-wescale/webservice-app:v3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ws-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: rest-api-ws
  selector:
    app: webservice
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ws-client
  annotations:
    kubernetes.io/ingress.class: "gce"
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: ws-service
    servicePort: 8080
  rules:
  - http:
      paths:
      - path: /v1/*
        backend:
          serviceName: ws-service
          servicePort: 8080
