apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webservice-deployment
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
      - name: app-backend
        image: slavayssiere/webservice-app:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webservice-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
      name: restapi
  selector:
    app: app-backend
  type: NodePort
