apiVersion: v1
data:
  password.txt: c2VjcmV0LXBhc3N3b3Jk
kind: Secret
metadata:
  creationTimestamp: 2017-12-04T17:31:54Z
  name: mysql-pass
  namespace: default
  resourceVersion: "96491"
  selfLink: /api/v1/namespaces/default/secrets/mysql-pass
  uid: 05680598-d919-11e7-837e-42010a84007f
type: Opaque
